version: "3"
services:
    backend:
        build: ./backend
        container_name: 'api-rentals'
        command: sh -c 'pip3 install -r requirements.txt; export FLASK_DEBUG=1;flask run; '
        ports: 
            - '5000:5000'
        volumes:
            - './backend/api:/backend/api'
        depends_on:
            - 'db-rentals'

    db-rentals:
        container_name: 'db-rentals'
        image: redis
        ports:
            - "6379:6379"

    frontend:
        build: ./frontend
        container_name: 'api-ui-rentals'
        command: sh -c 'pip3 install -r requirements.txt; flask run'
        ports:
            - '3000:3000'
        volumes:
            - ./frontend/api-ui:/frontend/api-ui
        depends_on:
            - "backend"
        stdin_open: true
        tty: true
