web: 
    build: .
    command: sh -c 'npm install; npm start'
    ports:
        - '3260:3260'
    volumes:
        - /home/exe/Documentos/Bases-de-Datos-NSQL/TP2/starwars/backend/api:/api
    links:
        - 'db:redis'
db:
    image: redis
    ports:
        - '6379:6379'
