version: "3"
services:
    frontend:
        build: ./frontend/galactic-blockchain-ui
        container_name: 'galactic-blockchain-ui'
        command: sh -c 'npm install; npm start'
        ports:
            - '3000:3000'
        volumes:
            - ./frontend/galactic-blockchain-ui:/frontend/galactic-blockchain-ui
        stdin_open: true